language: ruby
rvm:
  - 2.1.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rake spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.travis.yml config/application.yml
  - psql -c 'create database "movie-night_test"' -U postgres